name       : ctpl
version    : 0.3.4
release    : 3
source     :
    - http://download.tuxfamily.org/ctpl/releases/ctpl-0.3.4.tar.gz : 3a95fdd03437ed3ae222339cb0de2d2c1240d627faa6c77bf46f1a9b761729fb
license    : GPL-3.0-or-later
component  : programming.library
summary    : CTPL is a template engine library written in C
description: |
    CTPL is a template engine library written in C
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
